name = "Anubis"
license = "MIT"
description = "A minimal Hugo theme"
homepage = "https://github.com/mitrichius/hugo-theme-anubis"
tags = [
    "blog", 
    "responsive",
    "personal",
    "minimal", 
    "clean",
    "simple", 
    "light",
    "dark",
    "google-analytics",
    "mobile",
    "fast",
    "multilingual"
]
features = ["blog"]

[author]
    name = "Dmitry Kolosov"
    homepage = "http://dmitrykolosov.ru"
